### PR TITLE
Feature/extension methods

### PR DESCRIPTION
**Pull request by BrennanMcDonald**
Based off of the issue -https://github.com/anjdreas/UnitsNet/issues/37
I created initial scaffolding for extension methods that could be used for most units of measurement as well as fixed the image on the README.md

### CODE REVIEW

**Comment by anjdreas** [comment]
Sorry, I'm not notified of new commits to a PR. What is the state of this PR?

**Comment by anjdreas** [comment]
Just checking in. Do you still plan to complete this?

**Comment by BrennanMcDonald** [comment]
Im in school right now. I could put some time into it however I have a busy
schedule right now so I cant make time specifically for it.

**Comment by anjdreas** [comment]
No problem, just checking up on old PRs. Take your time, school is important! :-)

**Comment by anjdreas** [comment]
Fixed by 278d01c

**Pull request closed without merging**
