### PR TITLE
Make the units serializable via the use of data contract

### PR DESCRIPTION
**Pull request by tongbong**
Datacontract is part of dotnet portable, so it gives the ability to serialize in xml unitsnet objects.

It may be the answer to json serialization because datacontract offers a datacontractjsonserializer class.

Allthough I have tested it locally, the actual unit tests do not cover this use case.
We would need to create integration unit tests for that purpose.

### CODE REVIEW

**Comment by tongbong** [comment]
Might be a solution for anjdreas/master#92

**Comment by tongbong** [comment]
```    [Test]
        public void Foo2()
        {
            Length l1 = Length.From(10, LengthUnit.Centimeter);
            DataContractSerializer s = new DataContractSerializer(typeof(Length));
            string filePath = Environment.CurrentDirectory + "Length.xml";
            using (var stream = File.OpenWrite(filePath))
            {
                s.WriteObject(stream, l1);
            }
            Length l2;
            using (var stream = File.OpenRead(filePath))
            {
                l2 = (Length)s.ReadObject(stream);
            }
            Assert.AreEqual(l1, l2);
        }
```

The resulting xml file looks like this:
<Length xmlns="http://schemas.datacontract.org/2004/07/UnitsNet" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><_meters>0.1</_meters></Length>


Same test but with json:
```
        [Test]
        public void Foo3()
        {
            Length l1 = Length.From(10, LengthUnit.Centimeter);
            DataContractJsonSerializer s = new DataContractJsonSerializer(typeof(Length));
            string filePath = Environment.CurrentDirectory + "Length.json";
            using (var stream = File.OpenWrite(filePath))
            {
                s.WriteObject(stream, l1);
            }
            Length l2;
            using (var stream = File.OpenRead(filePath))
            {
                l2 = (Length)s.ReadObject(stream);
            }
            Assert.AreEqual(l1, l2);
        }
```
Resulting in a json file looking like this:
{"_meters":0.1}

It does not seem to be good enough for json...

**Comment by anjdreas** [comment]
Yes, this should work, but as per the discussion in #92 I am still a bit worried about breaking data compatibility at some point, say we decide to rename the private field to singular, or change the base unit to a different unit, or whatever. We could simply decide that, any breaking changes to units are simply not allowed, unless we bump the major version of the nuget or similar. I'd love some thoughts and feedback from more people on this though, I think it's easy to make a mistake here that will shoot someone horribly in the foot later.

**Comment by anjdreas** [comment]
If we do add support for serialization, we at least need to document what guarantees we put in that implementation, so anyone can make an informed choice on whether to use the built-in method or their own.

**Comment by anjdreas** [comment]
What are your thoughts on this? Should we leave it at the examples or implement data contract?

**Comment by tongbong** [comment]
I checked out #92, and I find it very elegant but to me it does not answer the question.
See I believe the serialized data should be auto descriptive meaning that the serialized data should contain everything needed for its deserialization. As a result two clients could serialize/deserialize despite using different libs and without any configuration.

If the above serialization data are not good enough, how about those ones:
- XML from data contract
```<Length xmlns="http://schemas.datacontract.org/2004/07/UnitsNet" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Value>0.1m</Value></Length>```
- JSon from data contract
```
{"Value":"0.1m"}
```

I think I am not wrong saying that an abbreviation is unique among the abbreviations from a unit type.
So in the Value property setter, we could imagine having that kind of parsing code:
```
public string Value
       {
            set 
           {
                Length l = Length.Parse(valueAsString, CultureInfo.InvariantCulture);
                _meters = l.Meters;
           }
      }
```

And the power of data contract makes possible to set the visibility of such property to internal, protected or private.

The client can choose wether he wants to use the xml data contract serializer or the json data contract serializer.

I will try later today or this week to propose such an exemple as in #92.

**Comment by anjdreas** [comment]
See #100 and #99 .

**Comment by anjdreas** [comment]
For your info, #100 and #101 are now closed and merged. Nugets UnitsNet.3.17.0 and UnitsNet.Serialization.JsonNet.1.0.0-alpha2 are out and support JSON serialization. 

Are you still looking to pursue datacontract serialization or will this satisfy your needs?

**Comment by tongbong** [comment]
Sorry I could not answer earlier, yes I will keep looking into it because my use case it to save quantities into some configuration files.

**Comment by anjdreas** [comment]
Just checking up on this, still planning to move forward with this PR?

**Comment by tongbong** [comment]
No plan to move forward anymore.
PR can be closed.

**Pull request closed without merging**
