### PR TITLE
Added DegreesPerMinute

### PR DESCRIPTION
**Pull request by eriove**
Degrees per minute is a common unit for rate of turn of a ship

### CODE REVIEW

**Comment by eriove** [comment]
Thanks!

I have another pull request incoming in a few minutes, so wait with releasing. Didn't expect you to merge so fast...

**Comment by anjdreas** [comment]
Too late :-)

**Comment by anjdreas** [comment]
Nuget 3.31 out.

**Comment by eriove** [comment]
I'll take my time with the next one then. Should have waited with pushing until both were done.

**Comment by anjdreas** [comment]
No worries, but nice if you can add a comment if you plan to do more PRs, then I can wait and grab them all in one go.

**Comment by eriove** [comment]
Will do that in the future. And thanks for the fast release. Appreciated by @ulflind

**Pull request merged**
