### PR TITLE
Handle ambiguous abbreviation parsing by throwing exception

### PR DESCRIPTION
**Pull request by neutmute**
As discussed on #132, this PR supports having abbreviations shared across units and throws when ambiguous.

I'll add some notes to the diff

### CODE REVIEW

**Comment by neutmute** [comment]
This should be good now - I haven't placed all abbreviations onto the units yet - just noticed you were busy reformatting all json files ;)

**Comment by anjdreas** [comment]
Sweet, looks good to me.

**Comment by anjdreas** [comment]
Nuget 3.26 is now out. 

I'm curious, did you get notified when I mentioned you in the github release?
https://github.com/anjdreas/UnitsNet/releases

**Comment by neutmute** [comment]
Awesome - thank you. 
Checking my emails - no, I only received notifications from your comments - not the release notes.

**Comment by anjdreas** [comment]
Ok good to know, I've always wondered the best way to notify contributors of a new release. Was hoping tagging in the release notes would do it, but guess not.

**Comment by neutmute** [comment]
If it helps, personally, I don't need the notification as I can see you release quickly after a merge so I just keep an eye out. On other library projects I have a personal myget feed that builds from my fork and I use that until the PR becomes official. Your fast releases and the nature of the library - not needing dogfooding before PR - save me that extra work.

It does give you more work though in manually balling up a release though, so you could automatically release on merge via nuget/teamcity. You lose the custom change log in the nuspec but it saves you from the manual work and contributors know a merge = a release.
If you want to bundle a few merges, perhaps have the default branch as `develop` with merges going into `develop`. A manual merge by yourself to `master` would trigger the CI build and release to nuget.

Just food for thought!

**Comment by anjdreas** [comment]
Thanks for the input. I did have the nuget publish automated in TeamCity a while back, but after changing branch style from gitflow back to github flow I didn't bother fixing it. It really is just bumping the .nuspec version and running two bat files to deploy, so the effort and frequency are too low to make me want to spend time automating it again.

I do want to keep a changelog though, so I'm thinking instead of putting it in the .nuspec, maybe just add it as annotation to the git tags instead. That should make it available on github too.

**Pull request merged**
