### PR TITLE
Migrate to VS2017 /MSBuild15 / .NET Standard / .NET Core

### LINKED ISSUE #255: Serialization with .NET core / .NET standard
While the main nuget package appears to work well with dotnet core, UnitsNet.Serialization.JsonNet refuses to install in a dotnet core app because it targets only the net35 framework. Is it possible to build a nuget package targeting dotnet core or dotnet standard, or are there any dependencies on incompatible packages or system APIs?

### PR DESCRIPTION
**Pull request by supermihi**
This PR resolves #255. See #257 for initial discussion.

TODO:
- [x] Verify Net35 project can be removed
- [x] Verify Portable40 project can be removed
- [ ] Verify signed packages "just work" when upgrading to new package (key file was converted)
- [ ] Set up build and tests for `UnitsNet.WindowsRuntimeComponent` (not ~sure yet if~ dotnet CLI compatible)
- [ ] See if `UnitsNet.sln` can be removed or renamed to `UnitsNet.WindowsRuntimeComponent.sln` if that is the only project that is not compatible with dotnet CLI.
- [ ] Set up .xml output for tests to `\Artifacts\Logs\<TestProjectName>.xml` files, currently [blocked by NUnit support in dotnet CLI](https://github.com/nunit/nunit3-vs-adapter/issues/323). XUnit seems to have found a workaround, so either wait for NUnit to do the same or switch to XUnit.
- [ ] Update README on new build targets (net35, netstandard1.0, WindowsRuntimeComponent)

### CODE REVIEW

**Comment by anjdreas** [comment]
Fixes #262 when merged.

**Comment by anjdreas** [comment]
Slowly moving towards completion. I spent some time redoing all the build scripts, but it now properly builds, tests, packs and publishes nugets via Appveyor CI.

https://www.nuget.org/packages/UnitsNet/3.65.0-alpha1
https://www.nuget.org/packages/UnitsNet.Signed/3.65.0-alpha1

What remains that I can think of:
- [ ] Verify Net35 project can be removed
- [ ] Verify Portable40 project can be removed
- [ ] Verify signed packages "just work" when upgrading to new package (key file was converted)
- [ ] Set up build and tests for `UnitsNet.WindowsRuntimeComponent` (not sure yet if dotnet CLI compatible)
- [ ] Set up .xml output for tests to `\Artifacts\Logs\<TestProjectName>.xml` files, currently [blocked by NUnit support in dotnet CLI](https://github.com/nunit/nunit3-vs-adapter/issues/323). XUnit seems to have found a workaround, so either wait for NUnit to do the same or switch to XUnit.

**Comment by supermihi** [comment]
Wow, now you put some effort into this! :) Would you mind pushing the current alpha version of the serialization package to nuget, because there's currently no version on nuget that works with dotnet core?

**Comment by anjdreas** [comment]
I had some issues building, but just pushed some manual nugets out now. They are prerelease versions `-alpha3`.

I must say, this whole vs2017 journey has not been entirely pleasant. It took a lot more time plow through than I'd like to admit, but I do like a lot of the concepts that `dotnet` CLI brings.

**Comment by anjdreas** [comment]
Currently running into this issue: https://github.com/Microsoft/vstest/issues/445#issuecomment-277592096

Tests refuse to run when the output dir is changed using `<BaseIntermediateOutputPath>` in the test project, and it is needed due to having multiple test projects in the same folder to share the source code.
Sigh.

**Comment by supermihi** [comment]
Sorry that I sort of "tricked" you into this effort. ;-) I naively assumed that it would be sufficient to remove a few lines in the `*.csproj` files and be happy with it. But I think it's worth the effort, as you say the direction Microsoft is heading with the `dotnet` CLI and the .NET Standard is a good one, though at the moment tooling and documentation ase pure chaos.

If there's any specific task you need help with please let me know; unless it's fixing the code-gerenating/build/pack/sign scripts, since I don't know Powershell and don't want to learn it ATM. :)

**Comment by anjdreas** [comment]
Hah, no worries :-) It would have to be done at some point anyway, and your effort really helped get over those initial roadblocks, so thanks for that!
Did the nugets work out as expected?

**Comment by supermihi** [comment]
Yes, I'm using the alpha version including JsonNet serialization in a dotnetcore app, works like a charm. Thanks!! :)

**Comment by anjdreas** [comment]
Cool! :-)

**Comment by anjdreas** [comment]
Merged! Phew.. a lot of hurdles on the windows runtime component stuff, as well as nunit and xunit with the new `dotnet test` and `dotnet xunit` commands. Did not like having multiple test projects in the same folder for one thing.

Thanks a lot for putting in the effort here. Hopefully this is now fairly future proof and not too many things change when dotnet CLI 2.0 goes RTM.

**Comment by supermihi** [comment]
Thank you as well for finishing this! I can only hope that Microsoft's approach with .NET standard will help to simplify multi-target libraries in the future ...

**Pull request merged**
