### PR TITLE
Added missing overloads for viscosity

### PR DESCRIPTION
**Pull request by eriove**
Added another missing overload. As you can tell I'm starting to use the library for calculations. It's probably a good idea to wait a couple of days before releasing anything. I might still find more missing overloads (I still think "this must be the last one" on each of them).

### CODE REVIEW

**Comment by anjdreas** [comment]
No problem, just let me know when it is ready to merge.
If all these PRs are related to overloads for viscosity then maybe unify them into a single PR?

**Comment by eriove** [comment]
You are right #159 and #161 are both related to viscosity. #160 is related indirectly, if you do calculation related to fluid mechanics you will need all of the overloads in these pull requests. Was so focused on one line at a time that I didn't notice. If you want I can merge them and create a new pull request and then add more overloads when I find them to that pull request.

**Comment by anjdreas** [comment]
Yes, a single PR will do fine.

**Comment by eriove** [comment]
Do you want me to merge #157 into this one too?

**Comment by anjdreas** [comment]
I suppose #157 and #160 can remain separate

**Comment by eriove** [comment]
I've now closed #159 

Will let you know when I think I won't fine more overloads

**Pull request closed without merging**
