### PR TITLE
Fix to the density conversions in the .json file

### PR DESCRIPTION
**Pull request by massonib**

### CODE REVIEW

**Comment by anjdreas** [comment]
Thanks!
I double checked the changes and look good, but I also glanced through the rest and found this. Can you check and correct if you agree?

```
"SingularName": "PoundPerCubicInch",
"PluralName": "PoundsPerCubicInch",
"FromUnitToBaseFunc": "x*27679.904710191",
"FromBaseToUnitFunc": "x/27679.904710191",
```

[Google](https://www.google.no/search?q=kilograms+per+cubicmeter+to+Tonnes+Per+CubicCentimeter&oq=kilograms+per+cubicmeter+to+Tonnes+Per+CubicCentimeter&aqs=chrome..69i57.9657j0j7&sourceid=chrome&ie=UTF-8#q=kilograms+per+cubicmeter+to+Pounds+Per+CubicInch) gives `1 kg / m³ = 3.61273e-5 lb/in³`
[unitjuggler.com](https://www.unitjuggler.com/convert-density-from-kgperm3-to-lbperin3.html) gives `3.6127298147753E-5 lb/in3`

**Comment by massonib** [comment]
1/3.61273e-5 = 27679.904710191. So at that point it is just semantics.

**Comment by massonib** [comment]
I have updated the density.JSON file to follow consistent conversion styling (e.g. always multiply for FromBaseToUnit and divide for FromUnitToBase). I'm not a computer with Powershell 3, so I couldn't run the code generator.

**Comment by anjdreas** [comment]
You are absolutely right, I missed that. I suppose it should go into the guidelines what form is the convention.

**Comment by anjdreas** [comment]
Nuget 3.38.1 out.

**Pull request merged**
